### ISSUE TITLE
Lab 9 peer review

### ISSUE THREAD

**Issue by GabrieleLucca** [AlbertoForesti/computational_intelligence#1]
I have to compliment you because your script is easy to read, and there are various comments that help with understanding. Additionally, you've included a README, so I had no difficulty grasping your script.

I think you've done an excellent job:
From using different types of implementations (evolution strategy, a genetic algorithm, and two island models: a simple one and a hierarchical one) to successfully plotting graphs for each instance of the problem. Great job!

I'm still curious about a few things (not criticisms):
1. Why did you use a beta distribution in the crossover (and if I understood correctly, why do you take only one value from a parent when you could perform a single mutation)?
2. Why didn't you implement early stopping? It could have significantly sped up the algorithm.

**Comment by AlbertoForesti** [comment]
Hi, thanks for the review! I try to answer your points:
1. I use the beta because, first, its support is [0,1] and it is well suited for taking a fraction of the length of the genome. Second, it is characterised by two parameters (a,b) which allow me to regulate mean and variance of the distribution as I like. I use the value that I sample from the beta to determine the fraction of the genome that I take from the first parent, therefore I don’t take just a single value in general. Sorry I should have made it evident :)
2. You are right I should have included it
