### ISSUE TITLE
Lab 9 Review

### ISSUE THREAD

**Issue by alialhousseini** [AlbertoForesti/computational_intelligence#2]
First of all, i have nothing to say about your work since it is a professional work and you tried to cover different techniques. So here I will try to propose some improvements that are not completely efficient since your is already done in a perfect way.

1. EvolutionTask Class: The complexity of the class could be reduced by splitting it into smaller, more focused sub-classes or functions.
2. Island Model(s):  The model can be improved by dynamically adjusting the migration rate based on the convergence status of the islands. (btw Bravo! for using it)
3. Mutation and Crossover: I think you covered these strategies enough but I will suggest that some additional strategies could lead to explore the search space more effectively.
4. Visualization: Well, this is the only thing that I can tell you that you have to improve it, I think that the visualization can be improved by adding axes labels and a legend and a grid background.

Discussion question: If I tell you that you can use a caching memory for reducing the fitness call, how you will implement it in your code? 

Best of luck, and amazing work!

**Comment by AlbertoForesti** [comment]
Hi Ali, thanks for your feedback :)

Your points are all very valid, I agree that my code would benefit from software engineering best practices as the EvolutionTask class is very long and some code is duplicated. I also agree that more sophisticated strategies in migration, mutation and crossover would improve my algorithm, but I decided to keep those simples to avoid tuning too many hyperparameters with low resources :)

Thanks for making me notice the lack of labels and legend, I should have included them

Your suggestion for caching is interesting, I think that surely it would help in avoiding to generate duplicate individuals. A straightforward implementation can be a Hash table in the EvolutionClass. But I also feel that there should be some implicit evaluation mechanism to get some fitness estimate also for similar but not identical individuals since the genome space is huge (2^1000).
